In [3]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import itertools

In [39]:
df = pd.read_csv('csv_input.csv', header=None).T
df.columns = df.iloc[0,:] # using the first row as column names 
df = df[1:].reset_index(drop=True) # drop the first column

# create columns needed
df.insert(1, 'wafer_id', df['lot'] + df['wafer'])
df['is_low_dilute'] = df['dilute mode'].apply(lambda x: 1 if x == 'LD' else 0).astype('int')

# specify which attributes we want
attribute_taken = ['attribute_owner', 'wafer_id', 'wafer', 'lot', 'temperature', 'cycle', 'pulse', 'purge', 'is_low_dilute', 'NH3 pressure', 'dep time']

df = df[attribute_taken]

# assume only one attribute owner in the read csv file
file_name = df['attribute_owner'][0]
df.to_csv(file_name, index=False)
df.head()

,attribute_owner,wafer_id,wafer,lot,temperature,cycle,pulse,purge,is_low_dilute,NH3 pressure,dep time
0,TiO99,NTA120300.00#1,#1,NTA120300.00,650,84,10,10.25,0,980,2024/12/31
1,TiO99,NTA120300.00#2,#2,NTA120300.00,650,83,10,10.25,0,980,2024/12/31
2,TiO99,NTA120300.00#3,#3,NTA120300.00,650,82,10,10.25,0,980,2024/12/31
3,TiO99,NTA120300.00#4,#4,NTA120300.00,650,81,10,10.25,0,980,2024/12/31
4,TiO99,NTA120300.00#5,#5,NTA120300.00,650,80,10,10.25,0,980,2024/12/31

# Procedures

1. Tune attribute reader to the actual case, create attribute files (with file name 'attribute.csv')
2. Put F1/XPS data together with the attribute file and run data extractor
3. Put the extracted data to model database
4. Run training